- host: all
  become: true
  tasks:
  - name: update apt
    apt:
      upgrade: true
      upgrade_cache: true
  - name: install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x' 
